# Generated by Django 2.1.14 on 2019-12-07 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessees', '0003_auto_20191207_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 7, 20, 2, 20, 540293)),
        ),
    ]
