# Generated by Django 2.1.14 on 2019-12-08 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessees', '0008_auto_20191207_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 8, 4, 27, 30, 745435)),
        ),
    ]
