# Generated by Django 2.1.14 on 2019-12-10 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessees', '0010_auto_20191208_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 10, 3, 34, 24, 580364)),
        ),
        migrations.AlterField(
            model_name='lessee',
            name='photo',
            field=models.ImageField(blank=True, default='img/avatar.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
