# Generated by Django 2.1.14 on 2019-11-20 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessor',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 20, 3, 54, 13, 716671)),
        ),
    ]
