# Generated by Django 2.1.14 on 2019-11-20 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0002_auto_20191120_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessor',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 20, 4, 1, 1, 237254)),
        ),
    ]
