# Generated by Django 2.1.14 on 2019-12-05 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0014_auto_20191205_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessor',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 5, 17, 46, 33, 491540)),
        ),
    ]
