# Generated by Django 2.1.14 on 2019-12-05 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0021_auto_20191205_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessor',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 5, 18, 5, 2, 248785)),
        ),
    ]
