# Generated by Django 2.1.14 on 2019-12-07 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0025_auto_20191206_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessor',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 7, 19, 59, 39, 629132)),
        ),
        migrations.AlterField(
            model_name='lessor',
            name='photo',
            field=models.ImageField(blank=True, default='img/default_avatar.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
