# Generated by Django 2.1.14 on 2019-12-07 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0027_auto_20191207_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessor',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 7, 20, 10, 25, 290099)),
        ),
        migrations.AlterField(
            model_name='lessor',
            name='photo',
            field=models.ImageField(blank=True, default='aerstands/static/img/avatar.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
