# Generated by Django 2.1.14 on 2019-12-08 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessors', '0032_auto_20191208_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessor',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 8, 4, 29, 28, 41941)),
        ),
        migrations.AlterField(
            model_name='lessor',
            name='photo',
            field=models.ImageField(blank=True, default='img/avatar.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
