# Generated by Django 2.1.14 on 2019-11-20 03:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('serial_num', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=400)),
                ('OEM_approved', models.CharField(max_length=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_available', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 20, 3, 42, 17, 916556))),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessors.Lessor')),
            ],
        ),
    ]
